// Package model holds the canonical types every race adapter and the daemon
// agree on.
package model

import "time"

// Race is the engine behind a character: Claude Code, Cursor, or Codex.
// Immutable for a character's whole life — its conversation lives in its
// engine's own store, so it can never become another engine's character.
// Codex has no adapter and stays unrepresented; the constant exists so the
// type is complete.
type Race string

const (
	RaceClaudeCode Race = "claude-code"
	RaceCodex      Race = "codex"
	RaceCursor     Race = "cursor"
)

// Class is the model a character runs (a Claude Code alias like "opus", or
// a Cursor model id). Changeable in principle — it is a flag passed when a
// process starts, not a property of the race.
type Class string

// Activity is what a character is doing right now. It says nothing about
// whether a process is alive for it — see the daemon's presence field,
// computed separately and never stored.
type Activity string

const (
	// ActivityReady is a character at camp with nothing to do: newly
	// created, or back from a quest that ended without a question.
	ActivityReady Activity = "ready"
	// ActivityWorking is a character out on a quest.
	ActivityWorking Activity = "working"
	// ActivityWaiting is a character back with a question, needing the
	// user to answer before it can continue.
	ActivityWaiting Activity = "waiting"
	// ActivityFailed is a character whose last quest ended badly, or whose
	// process disappeared while it was still marked working.
	ActivityFailed Activity = "failed"
)

// TerritoryMode is how a character's working directory relates to the repo
// it came from.
type TerritoryMode string

const (
	// TerritoryOwn is a git worktree LiveAgentsView created and
	// administers under ~/.liveagentsview/worktrees/.
	TerritoryOwn TerritoryMode = "own"
	// TerritoryShared is a directory the user picked, left exactly as it
	// is — LiveAgentsView runs no git command against it.
	TerritoryShared TerritoryMode = "shared"
)

// Territory is where a character's process actually runs. Source is the
// repo a worktree came from for TerritoryOwn; it equals Path for
// TerritoryShared.
type Territory struct {
	Mode   TerritoryMode `json:"mode"`
	Path   string        `json:"path"`
	Source string        `json:"source"`
	Branch string        `json:"branch"`
}

// Character is the durable party member the user creates and talks to
// across many quests. No field here says whether a process is alive for it
// — presence is observed from its pilot-runner control socket, never
// stored, see the daemon's API serializer and reconciler.
type Character struct {
	// ID is generated by LiveAgentsView and stable for the character's
	// whole life — it names its pilot-runner socket and transcript files.
	ID string `json:"id"`
	// SessionID is the provider-side conversation id, empty until the
	// first launch reports it (Claude Code's --session-id echoed back, or
	// cursor-agent's own assigned session id).
	SessionID   string    `json:"session_id"`
	Race        Race      `json:"race"`
	Class       Class     `json:"class"`
	Activity    Activity  `json:"activity"`
	Unread      bool      `json:"unread"`
	Territory   Territory `json:"territory"`
	Repo        string    `json:"repo"`
	Archived    bool      `json:"archived"`
	LastMessage string    `json:"last_message"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
